version: '3'

services:
  db:
    image: postgres
  web:
    env_file: .env
    build: .
    command: python3 src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
